# -*- coding: utf-8 -*-
"""sofi

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16yCsoWBRK0yacyyJGR1yfKC2xaWSXoRG
"""

import matplotlib as plt
import numpy as np
import pandas as pd
from sklearn import datasets,linear_model
from sklearn.model_selection import train_test_split

df = pd.read_excel('Height-Weight Data.xlsx')
# df

new_df = df.drop('Weight',axis='columns')
new_df

weight = df.Weight
weight

reg = linear_model.LinearRegression()
reg.fit(new_df,weight)

reg.predict([[3300]])

m = reg.coef_

b=reg.intercept_

reg.predict([[5000]])

height_df = new_df
height_df.head(3)

p = reg.predict(height_df)
p

height_df['Weight']=p
height_df

height_df.to_csv("prediction.csv")